### PR TITLE
Plot label adjustment

### PR DESCRIPTION
**Pull request by GbotemiB**
This PR introduces changes to the plot by putting the pypsa plots first, then the validation data next to it.

### CODE REVIEW

**Comment by yerbol-akhmetov** [comment]
Great @GbotemiB. Could you change the name of the validation script to results_validation as suggested by @danielelerede-oet?
Can you add code to output results in tabular form too? Maybe three different csv files? What do you think?

**Comment by GbotemiB** [comment]
@yerbol-akhmetov. Thank you for the comment. Having a table will be a great idea too.

**Comment by yerbol-akhmetov** [comment]
@GbotemiB, I have reverted the location of scripts._helper import. In windows, it is important to sys.path.append the path, and then only `scripts` folder start to be visible by script. 
`import sys`
`sys.path.append(os.path.abspath(os.path.join(__file__, "../../")))`
`from scripts._helper import mock_snakemake, update_config_from_wildcards, build_directory, \
                            load_pypsa_network, PLOTS_DIR, DATA_DIR `

**Comment by GbotemiB** [comment]
> @GbotemiB, I have reverted the location of scripts._helper import. In windows, it is important to append the path, and then only `scripts` folder start to be visible by import. `import sys` `sys.path.append(os.path.abspath(os.path.join(__file__, "../../")))` `from scripts._helper import mock_snakemake, update_config_from_wildcards, build_directory, \ load_pypsa_network, PLOTS_DIR, DATA_DIR `

@yerbol-akhmetov, Thank you for making this change. My code editor tries to rearrange it everytime.

**Review by yerbol-akhmetov — APPROVED** [review]
@GbotemiB, thanks for the PR. I have added changes like using output name of snakemake rule, and adding measurement unit for csv file. Please test it locally, then we can merge it.

**Pull request merged**
