### PR TITLE
update submodule

### PR DESCRIPTION
**Pull request by GbotemiB**
This PR updates the submodule to match the latest commit in OET fork.

### CODE REVIEW

**Review by danielelerede-oet — APPROVED** [review]
Hey Emmanuel, I guess the missing submodule update was the problem with the runs for the sector part of the model, is that correct?

**Comment by yerbol-akhmetov** [comment]
@GbotemiB, thanks. Can you please reupdate the submodule to point to oet/main? As suggested by @davide-f, oet/main was reset to follow pypsa-meets-earth main. While all changes that was committed in main are moved to another branch.

**Comment by GbotemiB** [comment]
> Hey Emmanuel, I guess the missing submodule update was the problem with the runs for the sector part of the model, is that correct?

I guess so. Some changes was made in upstream, which were not in our submodule. Updating should make it work.

**Comment by yerbol-akhmetov** [comment]
Merging the PR, thanks @GbotemiB

**Pull request merged**
